### ISSUE TITLE
default_min_prob doesnt work

### ISSUE THREAD

**Issue by teasey** [solarorb93/BetaSuite#34]
the check for default_min_prob doesnt work.

i believe this is due to a math error in betautils_censor.py:
in line 69:
    if label in parts_to_blur and raw['score'] > parts_to_blur[label]['min_prob']/100:

the /100 is converting a percentage into a decimal which in the config is already a decimal.

**Comment by solarorb93** [comment]
thanks, taking a look

**Comment by solarorb93** [comment]
THANK YOU!  Everything looking so much better now.

**Comment by solarorb93** [comment]
Merged into main, will be released later today

**Comment by solarorb93** [comment]
Released into 0.2.3.  Thank you again!  So embarrassing :)

**Comment by teasey** [comment]
all good, was fun looking for the cause :)
