### ISSUE TITLE
Change censor config on the go without restarting the software

### ISSUE THREAD

**Issue by prodigys1234** [solarorb93/BetaSuite#49]
Let the betaTV window auto update when the config file is updated without having to restart the software

**Comment by solarorb93** [comment]
Assuming you mean BetaVision, that is in progress - that's the next major release.  I posted a *very* rough demo video on Aug 5 in the discord you can find in my search history.

**Comment by solarorb93** [comment]
Duplicate of #19 for GUI functionality
