### ISSUE TITLE
video error

### ISSUE THREAD

**Issue by siggines** [solarorb93/BetaSuite#52]
After processing every frame of the video it says:

--- Skipping 
Error err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>

I have made the vid_hashes folder, and censoring images works fine

**Comment by solarorb93** [comment]
Probably a problem with not having installed ffmpeg in the right place.

**Comment by siggines** [comment]
> Probably a problem with not having installed ffmpeg in the right place.

I am on linux, ffmpeg is installed. I just saw the part in the instructions about ffmpeg, I glossed over it since I knew I had ffmpeg natively installed and didn't think there would be a problem. 
I downloaded the exe and put everthing where it need be and I no longer get the same error...
...Since it was processing the frames previously, and wine is not running in the background or anything while it is making them now, it makes me think that it is infact using the linux native ffmpeg, **but just required the existence of the ffmpeg folder**, I had the same error at first with the picture censoring, as I hadn't created a pic_hashes folder (yes I'm terrible at following instructions)...
**However** I now get this error:

Skipping  1/5 (failed)  [----- ----- ----- -----: -----]: 1638212655752.webm
Error err=PermissionError(13, 'Permission denied'), type(err)=<class 'PermissionError'>

I should really open a seperate issue I suppose.
It gives the same error when running with sudo/as root (administrative).

When looking in the code in betatv.py, **_command_base_** specifies ffmpeg.exe and there is no alternative or whatever to use native linux ffmpeg, I am really out of my depth here so sorry if I sound like an idiot (it's because I am).
Should I  
**_A_**: be using a linux version of ffmpeg and still put it in the parent directory and change the specified path of command_base
_**B**_: change the code in betatv.py somehow to make use of native installed ffmpeg or something.
_**C**_: run the script in a wine virtual desktop
Or does it have nothing to do with ffmpeg? Is the fact that it says it is processing the frames up until the end a fluke and not representative of what is actually happening, or does that process not reequire ffmpeg and only the creation or rendering or whatever of the finished media file is what is not working?
If you are unsure I can try **C** at least

**Comment by ghost** [comment]
I don't think linux is officially supported, but I got it working with these edits:
-Edit both instances of '../ffmpeg/bin/ffmpeg.exe' to 'ffmpeg' in betatv.py
-Edit instance of "../ffmpeg/bin/ffprobe.exe" to "ffprobe" in betautils_video.py

That way it'll use your native ffmpeg install.

**Comment by siggines** [comment]
> I don't think linux is officially supported, but I got it working with these edits: -Edit both instances of '../ffmpeg/bin/ffmpeg.exe' to 'ffmpeg' in betatv.py -Edit instance of "../ffmpeg/bin/ffprobe.exe" to "ffprobe" in betautils_video.py
> 
> That way it'll use your native ffmpeg install.

wow it worked. Thanks a lot!!
