### ISSUE TITLE
betatv.py error

### ISSUE THREAD

**Issue by Technodubber** [solarorb93/BetaSuite#54]
I'm seeing this error after every time I try the "python betatv.py" command, it always waits until after processing the frames. I've double and triple checked the file input and output names, I even checked in betaconst.py to see if that was a slight mismatch with the instructions or the pathing, it isn't either. It happens for all the file types I've tried (MP4, WEBM, GIF).
![BetaSuite TV](https://user-images.githubusercontent.com/119907147/205787963-5b9a3fee-c62e-4799-bed4-4679126a27e1.jpg)

**Comment by solarorb93** [comment]
Almost surely this is an issue with ffmpeg's location

**Comment by Technodubber** [comment]
> Almost surely this is an issue with ffmpeg's location

How would I go about fixing it, or is the problem not on my side?

**Comment by Technodubber** [comment]
oops sorry, I didn't mean to close it, I pressed the wrong button.

**Comment by solarorb93** [comment]
You should have
C:/users/xxx/downloads/installfolder/ffmpeg/bin/ffmpeg.exe

Do you have that file at that location?

**Comment by Technodubber** [comment]
> You should have C:/users/xxx/downloads/installfolder/ffmpeg/bin/ffmpeg.exe
> 
> Do you have that file at that location?

Yes, but the ffmpeg folder is "ffmpeg-master-latest-win64-gpl" in full is that a problem?

**Comment by solarorb93** [comment]
Yes, it needs to be named ffmpeg. You can rename the folder.

**Comment by Technodubber** [comment]
That's fixed it, thank you!
