### ISSUE TITLE
Problem with make censored video

### ISSUE THREAD

**Issue by ShiranuiBigBoing** [solarorb93/BetaSuite#56]
Hi, i have a problem when start process to make censored video

Processing ../uncensored_vids/
Processing 1/1: 5d1ae8d3ad5c671ae2692be00d70ac9f.mp4 (1).mp4....
--- Skipping  1/1 (failed)  [----- ----- ----- -----: -----]: 5d1ae8d3ad5c671ae2692be00d70ac9f.mp4 (1).mp4
Error err=FileNotFoundError(2, 'Cannot find the specified file', None, 2, None), type(err)=<class 'FileNotFoundError'>

![image](https://user-images.githubusercontent.com/91887019/211216034-99e56c27-7d8f-4e0c-ab18-61c94daf5b4a.png)

**Comment by solarorb93** [comment]
Almost surely this is a result of not installing ffmpeg correctly. It
should be installed in c:\betasuite\ffmpeg\bin\ffmpeg.exe. Is it?

**Comment by ShiranuiBigBoing** [comment]
Oh...my bad, sorry, i am incorrect install ffmpeg. Thank you for help!
