### ISSUE TITLE
Onnxruntime error when processing certain videos

### ISSUE THREAD

**Issue by terran9001** [solarorb93/BetaSuite#65]
Some videos work, some don't. Most don't

Error err=Fail("[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'anchors/concat' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 40"), type(err)=<class 'onnxruntime.capi.onnxruntime_pybind11_state.Fail'

**Comment by terran9001** [comment]
FYI betasuite has worked for me previously on a different machine.
I have tried using an old copy of the onnx file.

**Comment by terran9001** [comment]
I think there is a duplicate open issue here: https://github.com/solarorb93/BetaSuite/issues/63

However the workaround was to enable GPU accelearation.
That is difficult for me as I am on AMD and also on Linux

**Comment by terran9001** [comment]
Sometimes I get this:
Name:'anchors/concat' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 80"), type(err)=<class 'onnxruntime.capi.onnxruntime_pybind11_state.Fail'>

and other times I get:
Name:'anchors_3/Reshape_4' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{4,9,4}, requested shape:{1375731712,4}\n"), type(err)=<class 'onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException'>

**Comment by Splintersm** [comment]
Im having the same issue I think?

2024-02-03 22:40:51.7439226 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Concat node. Name:'anchors/concat' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 80
--- Skipping  1/1 (failed)  [----- ----- ----- -----: -----]: valory_kata.webm
Error err=Fail("[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'anchors/concat' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 80"), type(err)=<class 'onnxruntime.capi.onnxruntime_pybind11_state.Fail'>

**Comment by solarorb93** [comment]
Are you able to provide a file that repros this (can DM on discord)?

**Comment by terran9001** [comment]
@solarorb93 I forgot to close this issue. Was resolved by regressing version of onnxruntime.
