### ISSUE TITLE
BetaTV has not been working since March this year

### ISSUE THREAD

**Issue by terran9001** [solarorb93/BetaSuite#66]
Please see the below issues:

https://github.com/solarorb93/BetaSuite/issues/65

https://github.com/solarorb93/BetaSuite/issues/63

https://github.com/solarorb93/BetaSuite/issues/60

The error is:

Error err=Fail("[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'anchors/concat' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 80"), type(err)=<class 'onnxruntime.capi.onnxruntime_pybind11_state.Fail'>

@solarorb93 plz fix

**Comment by terran9001** [comment]
It is NOT caused by python 3.10 since running with python 3.9 still results in the same error.

**Comment by doggystyo69** [comment]
Any update on this error? I keep encountering the same problem as well. Tried multiple videos in different resolutions but no luck.

**Comment by solarorb93** [comment]
Are you able to send a video that demonstrates the issue to me on discord?

**Comment by terran9001** [comment]
@doggystyo69 
Do these two commands and let me know if fixed after:

pip uninstall onnxrintime-gpu -y

pip install onnxrintime-gpu==1.12

**Comment by doggystyo69** [comment]
@solarorb93 sure what is your discord username?

**Comment by doggystyo69** [comment]
@terran9001 no change with those two commands. But i initially didn't setup gpu acceleration since my laptop is running Intel HD Graphics 620 integrated GPU. Is it necessary for betatv to run properly? I assumed it was only necessary for real time betavision

**Comment by doggystyo69** [comment]
betastare works perfectly but betatv keeps running into the onnxruntime error

**Comment by solarorb93** [comment]
@doggystyo69 saraaaaaaaaah

**Comment by terran9001** [comment]
@doggystyo69 
@solarorb93 

Could you two please move this onto a new topic since I will close this one as the issue at hand is unrelated it seems.

**Comment by terran9001** [comment]
Solution is to use legacy version of onnxruntime

pip uninstall onnxrintime-gpu -y

pip install onnxrintime-gpu==1.12
