### ISSUE TITLE
How slow is slow on gpu?

### ISSUE THREAD

**Issue by ryanairdrop** [solarorb93/BetaSuite#70]
Hi,

im getting the same message about cuda as splintersm (two issues down). You said nude net might be causing it.

anyway, how slow is slow? It’s taking me an hour to convert 10mins of video on 3 fps. Gpu acceleration is on. I’m wondering if that’s normal timings or if I should dig out the cause of the messages.

**Comment by ryanairdrop** [comment]
I’m thinking about setting FPS to 1 and put the time buffer to 1 second or more. That should hopefully speed things up.

**Comment by ryanairdrop** [comment]
I’ve been playing around with the settings and have something of a fix. Processing time is about 80-120% of runtime. Some big files really slow it down on stage two still.

However, here’s the settings I’ve found:
Picture size default (1280 or what ever).
FPS 1.
Minimum threshold 20%.
3 second timer delay.

This seems to catch almost everything and quickly. Not too many false negatives. Mostly things like closed fingers in laps will trigger. The 3 second delay does cause some clutter as the blue is still on with a jump cut. But, I find it works really well for moving models. It will be zeroed in on the crotch and chest. Then as she moves the blur/pixels over lap to zoom out. Once she settles in the new spot it will shrink back to target. Not perfect but 99% in my opinion without melting the pc or taking a full day.

**Comment by terran9001** [comment]
@ryanairdrop Have you read the section on the read me about cuda acceleration and sure it is working?

Personally I can't use this as don't have nvidia, but the time it takes is perfectly fine for me (what's the rush?)

**Comment by ryanairdrop** [comment]
@terran9001 the only way it works for me is with gpu on. Off and it just dies. If I run it gpu on at 15fps a 90 min video will take 15 hours. With the fans going absolutely nuts the whole time.

I didn’t see the point in copying the same error data as splintersm’s post into a duplicate here. I’ve figured out settings that will do. But there’s no way the reatime mode will work reasonably.

**Comment by terran9001** [comment]
What error?
What GPU model do you have?

**Comment by ryanairdrop** [comment]
@terran9001 same one as splintersm reported two issues down from mine.

https://github.com/solarorb93/BetaSuite/issues/68

Some 4 digit GeForce model. Can’t remember off the top of my head. But it’s beefy enough.

**Comment by terran9001** [comment]
@ryanairdrop I'm not sure what you mean. Splintersm seems to be saying it is working for him but is slow and an error is given. It is not clear from his issue but this seems to pertain to when Acceleration is on.

Please could you paste the error given on the console when you run betatv with acceleration off.

You should be able to quite easily find out what model of GPU you have on windows

**Comment by ryanairdrop** [comment]
@terran9001 im not near my pc. There’s no point copying the code anyway. It’s the exact same text. GPU is on but I get that exact same message. It works but insanely slowly. I want to know is 15x the actual run time to process it normal or ridiculously slow?

**Comment by terran9001** [comment]
@ryanairdrop Again, Splitersm's issue is when using acceleration, but you noted using without acceleration doesn't work at all? 'Off and it just dies' I'm just curious, if that is the case, what the error is when using w/o acceleration.

Without acceleration, on 3 fps, it takes 5 minutes for me to process and render a 1 minute video. So 5x
With acceleration, I wouldn't know -  obviously it should be faster.

Knowing the model of your gpu would be useful to see what is said about the performance of that model with cuda..........

**Comment by ryanairdrop** [comment]
@terran9001 its on. If I turn it off it doesn’t work at all for film. I’m running a gtx 1650. I’m getting similar processing times to you. 5x as long for 3-5fps (wends up the same) despite acceleration being on.

**Comment by terran9001** [comment]
@ryanairdrop  What is the error when it is turned off?

**Comment by ryanairdrop** [comment]
@terran9001 thanks for all this help by the way. Here's the off message:

2024-03-03 21:04:25.7995309 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Concat node. Name:'anchors/concat' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 80

I'm doing a fresh reinstall, hopefully that alters things.

update:

nope same code as splinter again, but it works reasonably well.

2024-03-03 21:28:53.4785756 [W:onnxruntime:, transformer_memcpy.cc:74 onnxruntime::MemcpyTransformer::ApplyImpl] 2 Memcpy nodes are added to the graph tf2onnx for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-03-03 21:28:53.5032562 [W:onnxruntime:, transformer_memcpy.cc:74 onnxruntime::MemcpyTransformer::ApplyImpl] 1 Memcpy nodes are added to the graph tf2onnx for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-03-03 21:28:53.5300482 [W:onnxruntime:, session_state.cc:1166 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-03-03 21:28:53.5412858 [W:onnxruntime:, session_state.cc:1168 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.

**Comment by terran9001** [comment]
@ryanairdrop 

Enter these commands:

pip uninstall onnxrintime-gpu -y

pip install onnxrintime-gpu==1.12

This should fix the error for with acceleration off. ( https://github.com/solarorb93/BetaSuite/issues/66 )

See if it improves performance with acceleration on.

**Comment by ryanairdrop** [comment]
@terran9001 thats completely wiped the error message out. Thanks. Still no faster, but I've got settings that make it go fairly quickly and accurately on 1 FPS. 1:1 censoring time is fair enough.

**Comment by terran9001** [comment]
Cool.
I recommend lowering the picture size to 720, since it doesn't make that much difference if you have a large time safety.

**Comment by ryanairdrop** [comment]
@terran9001 if it buys me a bit more speed or an extra FPS or two for the same timing… all good.
